spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huseyin_aydin_db
    username: root
    password: toor
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true