DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE(
	ID INT PRIMARY KEY, 
	NAME VARCHAR(255)
);

INSERT INTO EMPLOYEE VALUES(1, 'Zımzımettin');
INSERT INTO EMPLOYEE VALUES(2, 'Şebelebelebelebettin');