FROM openjdk:11
ADD target/spring-boot-docker-mysql-crud-example-demo-0.0.1-SNAPSHOT.jar spring-boot-docker-mysql-crud-example-demo.jar
EXPOSE 8085
ENTRYPOINT ["java", "-jar", "spring-boot-docker-mysql-crud-exampl-demo.jar"]