#spring:
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: huso-group_1
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages : tr.com.huseyinaydin.dto



server:
  port: 9292